### ISSUE TITLE
Exception Resolving RMQConnectionFactory from WildFly 16.0.0 JNDI

### ISSUE THREAD

**Issue by joepietrzak** [rabbitmq/rabbitmq-jms-client#109]
Trying to resolve ConnectionFactory from remote JNDI on Wildfly (16.0.0-Final) results in an exception while unmarshalling.

The calling code is very simple:
```
    Properties environmentParameters = new Properties();
    environmentParameters.put(Context.INITIAL_CONTEXT_FACTORY, "org.wildfly.naming.client.WildFlyInitialContextFactory");
    environmentParameters.put(Context.PROVIDER_URL, "remote+http://mywildflyhost:8080");
    namingContext = new InitialContext(environmentParameters);
    ConnectionFactory connFactory = (ConnectionFactory) ctx.lookup("jms/ConnectionFactory");
```

the Connection Factory as defined in standalone-full.xml on my WildFly server:
```
                <object-factory name="java:jboss/exported/jms/ConnectionFactory" module="org.jboss.genericjms.provider" class="com.rabbitmq.jms.admin.RMQObjectFactory">
                    <environment>
                        <property name="className" value="javax.jms.ConnectionFactory"/>
                        <property name="uri" value="amqp://user:pass@:myrmqhost:5672"/>
                    </environment>
                </object-factory>
```

I defined the org.jboss.genericjms.provider module with the following module.xml
```
<module name="org.jboss.genericjms.provider" xmlns="urn:jboss:module:1.5">
    <resources>
       <resource-root path="."/>
        <resource-root path="amqp-client-5.7.0.jar"/>
        <resource-root path="rabbitmq-jms-1.11.2.jar"/>
	<resource-root path="slf4j-api-1.7.25.jar"/>
    </resources>
    <dependencies>
      <module name="javax.api"/> 
      <module name="javax.jms.api"/>
    </dependencies>
</module>
```

This is the exception I get (ActiveBatch is the calling code):
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Asci.ActiveBatch.Runtime.Messaging.CommandHandler.invoke(Unknown Source)
	at Asci.ActiveBatch.Integration.HostDomainCommandService.Invoke(Unknown Source)
	at Asci.ActiveBatch.Integration.HostDomainCommandService.Invoke(Unknown Source)
	at Asci.ActiveBatch.Integration.IntegrationService.Invoke(Unknown Source)
Caused by: javax.naming.CommunicationException: WFNAM00020: Remote naming operation failed [Root exception is java.io.EOFException: Read past end of file]
	at org.wildfly.naming.client.remote.RemoteClientTransport.lookup(RemoteClientTransport.java:261)
	at org.wildfly.naming.client.remote.RemoteContext.lambda$lookupNative$0(RemoteContext.java:190)
	at org.wildfly.naming.client.NamingProvider.performExceptionAction(NamingProvider.java:222)
	at org.wildfly.naming.client.remote.RemoteContext.performWithRetry(RemoteContext.java:100)
	at org.wildfly.naming.client.remote.RemoteContext.lookupNative(RemoteContext.java:188)
	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:74)
	at org.wildfly.naming.client.store.RelativeFederatingContext.lookupNative(RelativeFederatingContext.java:58)
	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:74)
	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:60)
	at org.wildfly.naming.client.AbstractFederatingContext.lookup(AbstractFederatingContext.java:66)
	at org.wildfly.naming.client.WildFlyRootContext.lookup(WildFlyRootContext.java:144)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at Asci.ActiveBatch.JMSAgent.JMSConsumer.receiveMsg(Unknown Source)
	at Asci.ActiveBatch.JMSAgent.JMSManager.receiveMsg(Unknown Source)
	at Asci.ActiveBatch.JMSAgent.JMSService.ReceiveMessageHandler(Unknown Source)
	... 8 more
Caused by: java.io.EOFException: Read past end of file
	at org.jboss.marshalling.SimpleDataInput.eofOnRead(SimpleDataInput.java:151)
	at org.jboss.marshalling.SimpleDataInput.readUnsignedByteDirect(SimpleDataInput.java:294)
	at org.jboss.marshalling.SimpleDataInput.readUnsignedByte(SimpleDataInput.java:249)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220)
	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853)
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1767)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:205)
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
	at org.wildfly.naming.client.remote.RemoteClientTransport.lookup(RemoteClientTransport.java:243)
	... 22 more
Caused by: an exception which occurred:
	in field com.rabbitmq.jms.admin.RMQConnectionFactory.amqpConnectionFactoryPostProcessor
	in object com.rabbitmq.jms.admin.RMQConnectionFactory@6293abcc
	in object of type com.rabbitmq.jms.admin.RMQConnectionFactory
```

This seems to be caused by a problem with unmarshalling the Consumer field amqpConnectionFactoryPostProcessor added with this commit
https://github.com/rabbitmq/rabbitmq-jms-client/commit/da91f5d48e1105bc4f893144336d3ea57fa30964
I can verify that using rabbitmq-jms-client-1.9.0 I **do not** receive this exception.
An example configuration for WildFly is shown on https://www.rabbitmq.com/jms-client.html so even if this is actually a bug in WildFly code, I am of the opinion that the RabbitMQ JMS Client should work around that (especially being that the JMS Client worked seamlessly with WildFly prior to 1.10.0)

**Comment by michaelklishin** [comment]
The commit above simply added a new field. If there was a serialised version of a `com.rabbitmq.jms.admin.RMQConnectionFactory` stored somewhere, it is likely not going to deserialise successfully. There is no way this client can work around that and not adding new fields is not an option.

Please start a mailing list thread with an example repository we can use to reproduce. We'd like to support WildFly 1.10 but the change is quite trivial and I am not convinced that we can do much about such issues (at least if the hypothesis I have is correct).

**Comment by acogoluegnes** [comment]
I think the serialization crashes because the default, no-op value for `RMQConnectionFactory#amqpConnectionFactoryPostProcessor` is not serializable. Versions after 1.9 introduced a few other properties to `RMQConnectionFactory` and their default, no-op values are not serializable (`metricsCollector`, `amqpConnectionFactoryPostProcessor`, `sendingContextConsumer`, `receivingContextConsumer`).

The easiest workaround is to assign null values to these properties. They should be null-proof, except `metricsCollector`, but you can give it a try. The next workaround is to assign no-op values that implements serializable (create such classes and assign instances of them to the connection factory).

These are just temporary workarounds to make sure my assumption is correct, we can obviously make those default implementations serializable and specify in the Javadoc that the instances for these properties must be serializable in some specific environments (e.g. JNDI).

Problem solved if WildFly needs the connection factory to be serializable for some reasons (e.g. transmitting it over the network). The problem is different with the following scenario: the connection factory is serialized (stored somewhere) with some JMS Client version and then must be deserialized (read from storage) and restored with another JMS Client version. This isn't only about serialization anymore, but also about the compatibility of serialization between versions. This can be solved as well but seems overkill for this case.

Thanks for the provided information, I would not mind a sample project and instructions to reproduce and check some potential fixes (I'm not familiar with WildFly).

**Important note:** I see you use the AMQP Client 5.7.0. The 1.x series of the JMS client are compiled against the 4.x series of the AMQP client (to keep the compatibility with Java 1.6). AMQP client 4.x and 5.x are not compatible, so there's no guarantee that JMS Client 1.x works with AMQP Client 5.x. You should use AMQP Client 4.8.3 with JMS client 1.11.2 (or the latest of AMQP Client 4.x, that is 4.11.0 right now).
