### ISSUE TITLE
NPE if a received message is marked as "Redelivered" but no header is given

### ISSUE THREAD

**Issue by chbriem** [rabbitmq/rabbitmq-jms-client#325]
### Describe the bug

When receiving a message in "amqp mode" with a "Redelivered" flag set, and the given message does _not_ contain _any_ headers, then a NPE is thrown.

### Reproduction steps

1. Initialize the "RMQDestination" with Routing Key and Exchange Name ("amqp mode").
2. Put a message in the queue, with "relivered" flag set and _no_ headers.
3. Try to receive the message

### Expected behavior

No NPE is thrown, and the code runs into the branch where `deliveryCount == null`, which sets the `JMSXDeliveryCount` is set to "2".

### Additional context

Stacktrace (shortened): 
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "com.rabbitmq.client.AMQP$BasicProperties.getHeaders()" is null
	at com.rabbitmq.jms.client.RMQMessage.handleJmsRedeliveredAndDeliveryCount(RMQMessage.java:886) ~[rabbitmq-jms.jar:2.8.0]
	at com.rabbitmq.jms.client.RMQMessage.convertAmqpMessage(RMQMessage.java:866) ~[rabbitmq-jms.jar:2.8.0]
	at com.rabbitmq.jms.client.RMQMessage.convertMessage(RMQMessage.java:835) ~[rabbitmq-jms.jar:2.8.0]
	at com.rabbitmq.jms.client.RMQMessageConsumer.receive(RMQMessageConsumer.java:358) ~[rabbitmq-jms.jar:2.8.0]
	at com.rabbitmq.jms.client.RMQMessageConsumer.receive(RMQMessageConsumer.java:272) ~[rabbitmq-jms.jar:2.8.0]
```

**Comment by michaelklishin** [comment]
This client assumes that the value is always set because it is always set by RabbitMQ itself (to `false` by default).

There's no harm in being more defensive, you are welcome to submit a PR. This is open source software after all.
