### ISSUE TITLE
JMeter JMS Publisher usage

### ISSUE THREAD

**Issue by typekpb** [rabbitmq/rabbitmq-jms-client#46]
I'm trying to do some perf testing with JMeter JMS.
On the server I have `rabbitmq_jms_topic_exchange` plugin enabled.

What is the proper JMeter Initial Context Factory to be set?
Tried with following:
![image](https://user-images.githubusercontent.com/499820/38329484-3f0cc8f8-384e-11e8-8906-5359dea08331.png)

However ended up in (expected) exception:

	javax.naming.NamingException: javax.naming.NoInitialContextException: Cannot instantiate class: com.rabbitmq.jms.admin.RMQConnectionFactory [Root exception is java.lang.ClassCastException: com.rabbitmq.jms.admin.RMQConnectionFactory cannot be cast to javax.naming.spi.InitialContextFactory]
		at org.apache.jmeter.protocol.jms.client.InitialContextFactory.lookupContext(InitialContextFactory.java:69) ~[ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.client.InitialContextFactory.getContext(InitialContextFactory.java:156) ~[ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.client.ReceiveSubscriber.<init>(ReceiveSubscriber.java:231) ~[ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.client.ReceiveSubscriber.<init>(ReceiveSubscriber.java:170) ~[ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.sampler.SubscriberSampler.initListenerClient(SubscriberSampler.java:119) ~[ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.sampler.SubscriberSampler.initClient(SubscriberSampler.java:346) [ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.protocol.jms.sampler.SubscriberSampler.threadStarted(SubscriberSampler.java:336) [ApacheJMeter_jms.jar:4.0 r1823414]
		at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:676) [ApacheJMeter_core.jar:4.0 r1823414]
		at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994) [jorphan.jar:4.0 r1823414]
		at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:977) [jorphan.jar:4.0 r1823414]
		at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:644) [ApacheJMeter_core.jar:4.0 r1823414]
		at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:632) [ApacheJMeter_core.jar:4.0 r1823414]
		at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:246) [ApacheJMeter_core.jar:4.0 r1823414]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

I don't see any `InitialContextFactory` implementation in the sources out here. Or is jmeter JMS sampler not usable at all here?

**Comment by michaelklishin** [comment]
This depends on what exactly JMeter JMS plugin does and what JMS version it requires. There can be incompatibilities but the exception happens so early it's a guess:

> java.lang.ClassCastException: com.rabbitmq.jms.admin.RMQConnectionFactory cannot be cast to javax.naming.spi.InitialContextFactory

If steps to reproduce were provided on rabbitmq-users, perhaps we'd be able to suggest something.

**Comment by michaelklishin** [comment]
So far it looks like the "initial context factory" field expects a context factory, not a connection one.
